### ISSUE TITLE
Issue with asent runnung spacy pipeline in multiprocessing

### ISSUE THREAD

**Issue by aholovenko** [KennethEnevoldsen/asent#158]
I get an issue trying to run the spacy pipeline with asent component using multiprocessing.

## How to reproduce the behaviour

```
documents = pd.Series(['I am trying to run this....', 'Also this one.'])

model = spacy.load('en_core_web_sm')
model.add_pipe('sentencizer', first=True)
model.add_pipe('asent_en_v1')

for doc in model.pipe(documents, batch_size=16, n_process=2):
    pass
```

As a result I get 
```
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/my_test_repo/lib/python3.10/site-packages/spacy/language.py", line 1694, in _multiprocessing_pipe
    self.default_error_handler(
  File "/home/username/.pyenv/versions/my_test_repo/lib/python3.10/site-packages/spacy/util.py", line 1724, in raise_error
    raise e
ValueError: [E871] Error encountered in nlp.pipe with multiprocessing:

Traceback (most recent call last):
  File "/home/username/.pyenv/versions/my_test_repo/lib/python3.10/site-packages/spacy/language.py", line 2303, in _apply_pipes
    byte_docs = [(doc.to_bytes(), doc._context, None) for doc in docs]
  File "/home/username/.pyenv/versions/my_test_repo/lib/python3.10/site-packages/spacy/language.py", line 2303, in <listcomp>
    byte_docs = [(doc.to_bytes(), doc._context, None) for doc in docs]
  File "spacy/tokens/doc.pyx", line 1348, in spacy.tokens.doc.Doc.to_bytes
  File "spacy/tokens/doc.pyx", line 1411, in spacy.tokens.doc.Doc.to_dict
  File "/home/username/.pyenv/versions/my_test_repo/lib/python3.10/site-packages/spacy/util.py", line 1352, in to_dict
    serialized[key] = getter()
  File "spacy/tokens/doc.pyx", line 1408, in spacy.tokens.doc.Doc.to_dict.lambda20
  File "/home/username/.pyenv/versions/my_test_repo/lib/python3.10/site-packages/srsly/_msgpack_api.py", line 14, in msgpack_dumps
    return msgpack.dumps(data, use_bin_type=True)
  File "/home/username/.pyenv/versions/my_test_repo/lib/python3.10/site-packages/srsly/msgpack/__init__.py", line 55, in packb
    return Packer(**kwargs).pack(o)
  File "srsly/msgpack/_packer.pyx", line 285, in srsly.msgpack._packer.Packer.pack
  File "srsly/msgpack/_packer.pyx", line 291, in srsly.msgpack._packer.Packer.pack
  File "srsly/msgpack/_packer.pyx", line 288, in srsly.msgpack._packer.Packer.pack
  File "srsly/msgpack/_packer.pyx", line 264, in srsly.msgpack._packer.Packer._pack
  File "srsly/msgpack/_packer.pyx", line 282, in srsly.msgpack._packer.Packer._pack
TypeError: can not serialize 'DocPolarityOutput' object

python-BaseException

Process finished with exit code 1
```

## Your Environment

* asent Version Used: 0.7.6
* Operating System:Ubuntu 20.04.6 LTS
* Python Version Used: 3.10.0
* spaCy Version Used: 3.6.1
* Environment Information: en-core-web-sm==3.6.0 pandas==1.5.3

Will be very glad with any help with this issue.

**Comment by aholovenko** [comment]
Environment that works ok: 
```spacy~=3.4.4 asent~=0.6.1```

**Comment by KennethEnevoldsen** [comment]
Ah right. Initially, this package wasn't intended to be run in parallel as everything was implemented as getters (but the most recent addition #155) changed that, but does indeed introduce this problem. However, the old  change didn't really run anything in parallel (you just ran it when you called the `doc._.polarity`

This is simply a lack of implementing the serialization hook for the data classes (e.g. DocPolarityOutput). Which is not entirely trivial.

**A question before I implement anything:**
- Is parallelization needed -  i.e. is the pipeline too slow? Often for rule-based components like this one, the cost of serialization is higher than the gain of parallelization.

**Comment by KennethEnevoldsen** [comment]
Hi @aholovenko the newest version of asent adds support for multiprocessing.

**Comment by aholovenko** [comment]
@KennethEnevoldsen Thank so much!
